# Add your own tasks in files placed in lib/tasks ending in .rake,
# for example lib/tasks/capistrano.rake, and they will automatically be available to Rake.

require File.expand_path('../config/application', __FILE__)
require 'rake'

DummyApp::Application.load_tasks

Rake::TestTask.new(:test) do |t|
  t.libs << 'app/controllers' << 'app/mailers' << 'app/models' << 'lib'
  t.pattern = 'test/**/*_test.rb'
  t.verbose = true
end

